server:
  port: 9025
  
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:9999/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:{random.value}
    preferIpAddress: true

spring:
  datasource:
    url: jdbc:postgresql://${MY_ENDPOINT}/Post_Service
    username: ${MY_USERNAME}    
    password: ${MY_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    
